#!/usr/bin/env python3
"""Compile the first real Castle Area 1 root into a compact Saturn C bank.

This is deliberately a narrow M3 bridge: it consumes the checked source
display-list flattening, retains only the opaque root layer, and serializes
the exact source positions/topology and Fast3D texture state in first-use
order. It does not invent a replacement level format or interpret level
scripts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from extract_castle_area import extract


def compile_opaque(area: Path) -> dict[str, object]:
    """Return a deterministic, indexed representation of Area 1 opaque roots."""
    scene = extract(area)
    positions: list[tuple[int, int, int]] = []
    position_index: dict[tuple[int, int, int], int] = {}
    triangles: list[tuple[int, int, int]] = []
    sources: list[str] = []
    triangle_textures: list[str | None] = []
    triangle_uv: list[tuple[tuple[int, int], tuple[int, int], tuple[int, int]]] = []
    triangle_tiles: list[dict[str, object] | None] = []
    for triangle in scene["triangles"]:
        if triangle["layer"] != "LAYER_OPAQUE":
            continue
        indices: list[int] = []
        for raw in triangle["positions"]:
            position = tuple(int(value) for value in raw)
            index = position_index.get(position)
            if index is None:
                index = len(positions)
                position_index[position] = index
                positions.append(position)
            indices.append(index)
        triangles.append(tuple(indices))
        sources.append(str(triangle["source_display_list"]))
        triangle_textures.append(None if triangle["texture"] is None else str(triangle["texture"]))
        triangle_uv.append(tuple(tuple(int(value) for value in uv) for uv in triangle["uv"]))
        triangle_tiles.append(triangle["tile"])
    textures = sorted({texture for texture in triangle_textures if texture is not None})
    texture_indices = [0xFF if texture is None else textures.index(texture) for texture in triangle_textures]
    return {
        "schema": "sm64-saturn-castle-static-ir",
        "version": 1,
        "name": "castle_inside_area_1_opaque_root",
        "source": "levels/castle_inside/areas/1",
        "layer": "LAYER_OPAQUE",
        "vertex_count": len(positions),
        "triangle_count": len(triangles),
        "source_display_lists": sorted(set(sources)),
        "textures": textures,
        "texture_indices": texture_indices,
        "positions": positions,
        "triangles": triangles,
        "uv": triangle_uv,
        "tile_state": triangle_tiles,
        "texture_state_version": 2,
        "limits": ["Opaque root only", "No alpha/decal layers", "No visibility or clipping"],
    }


def write_header(bank: dict[str, object], output: Path) -> None:
    positions = bank["positions"]
    triangles = bank["triangles"]
    texture_indices = bank["texture_indices"]
    uv = bank["uv"]
    lines = [
        "/* Generated by tools/saturn/compile_castle_area.py; do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        f"#define SM64_CASTLE_AREA1_VERTEX_COUNT {len(positions)}U",
        f"#define SM64_CASTLE_AREA1_OPAQUE_TRIANGLE_COUNT {len(triangles)}U",
        f"#define SM64_CASTLE_AREA1_TEXTURE_COUNT {len(bank['textures'])}U",
        "#define SM64_CASTLE_AREA1_TEXTURE_NONE 0xFFU",
        "static const int16_t sm64_castle_area1_vertices[SM64_CASTLE_AREA1_VERTEX_COUNT][3] = {",
    ]
    lines.extend(f"    {{{x}, {y}, {z}}}," for x, y, z in positions)
    lines.append("};")
    lines.append("static const uint16_t sm64_castle_area1_triangles[SM64_CASTLE_AREA1_OPAQUE_TRIANGLE_COUNT][3] = {")
    lines.extend(f"    {{{a}, {b}, {c}}}," for a, b, c in triangles)
    lines.append("};")
    lines.append("static const uint8_t sm64_castle_area1_triangle_texture[SM64_CASTLE_AREA1_OPAQUE_TRIANGLE_COUNT] = {")
    lines.extend("    " + ", ".join(f"{value}U" for value in texture_indices[offset:offset + 16]) + "," for offset in range(0, len(texture_indices), 16))
    lines.append("};")
    lines.append("static const int16_t sm64_castle_area1_triangle_uv[SM64_CASTLE_AREA1_OPAQUE_TRIANGLE_COUNT][3][2] = {")
    lines.extend(f"    {{{{{a}, {b}}}, {{{c}, {d}}}, {{{e}, {f}}}}}," for (a, b), (c, d), (e, f) in uv)
    lines.append("};")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--area", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    bank = compile_opaque(args.area)
    write_header(bank, args.output)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(bank, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
