#!/usr/bin/env python3
"""Emit the generated C fragment bank used by the optional sourceboot tier."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def emit(mesh: dict[str, object], scene: dict[str, object]) -> str:
    bsp = scene["bsp"]
    positions: list[list[int]] = []
    primitives: list[dict[str, object]] = []
    for fragment in scene["fragments"]:
        source = mesh["primitives"][int(fragment["source_primitive"])]
        material = mesh["materials"][int(source["material"])]
        points = [list(map(int, point)) for point in fragment["positions"]]
        textured = bool(fragment["textured"])
        indices = [len(positions) + offset for offset in range(3)]
        positions.extend(points)
        # sample_triangle() and castleviewer lower triangles as A/B/C/C.
        # The offline affine companion is deliberately not a runtime vertex.
        fourth = indices[2]
        primitives.append({
            "indices": (indices[0], indices[1], indices[2], fourth),
            # Keep the compiled Mesh IR primitive identity, not the source
            # triangle ordinal. The BSP reference stream is keyed by this
            # identity, so fragments can inherit its camera order.
            "source0": int(fragment["source_primitive"]),
            "source1": 0xFFFF,
            "rgb": material["rgb555"],
            "textured": 1 if textured else 0,
            "tile_size": 16 if textured else 0,
            "tile_offset": int(fragment["tile_offset"]),
            "clut_offset": int(fragment["clut_offset"]),
        })
    lines = [
        "/* Generated by tools/saturn/emit_bob_bsp_fragments.py; do not edit. */",
        "#ifndef SM64_SATURN_BOB_BSP_FRAGMENTS_H",
        "#define SM64_SATURN_BOB_BSP_FRAGMENTS_H",
        "#include <stdint.h>",
        f"#define SM64_SATURN_BOB_FRAGMENT_POSITION_COUNT {len(positions)}U",
        f"#define SM64_SATURN_BOB_FRAGMENT_PRIMITIVE_COUNT {len(primitives)}U",
        f"#define SM64_SATURN_BOB_FRAGMENT_BSP_NODE_COUNT {bsp['node_count']}U",
        f"#define SM64_SATURN_BOB_FRAGMENT_BSP_REF_COUNT {bsp['ref_count']}U",
        "typedef struct sm64_saturn_bob_fragment_primitive {",
        "    uint16_t indices[4]; uint16_t source0; uint16_t source1; uint8_t rgb[3];",
        "    uint8_t textured; uint8_t tile_size; uint32_t tile_offset;",
        "    uint32_t clut_offset;",
        "} sm64_saturn_bob_fragment_primitive_t;",
        "static const int32_t sm64_saturn_bob_fragment_positions[SM64_SATURN_BOB_FRAGMENT_POSITION_COUNT][3] = {",
    ]
    lines.extend("    {%d, %d, %d}," % tuple(point) for point in positions)
    lines += [
        "};",
        "static const int32_t sm64_saturn_bob_fragment_bsp_planes[SM64_SATURN_BOB_FRAGMENT_BSP_NODE_COUNT][3] = {",
    ]
    lines.extend("    {%d, %d, %d}," % tuple(node["plane"])
                 for node in bsp["nodes"])
    lines += [
        "};",
        "static const int64_t sm64_saturn_bob_fragment_bsp_distances[SM64_SATURN_BOB_FRAGMENT_BSP_NODE_COUNT] = {",
    ]
    lines.extend("    INT64_C(%d)," % node["distance"] for node in bsp["nodes"])
    lines += [
        "};",
        "static const int16_t sm64_saturn_bob_fragment_bsp_children[SM64_SATURN_BOB_FRAGMENT_BSP_NODE_COUNT][2] = {",
    ]
    lines.extend("    {%d, %d}," % tuple(node["children"])
                 for node in bsp["nodes"])
    lines += [
        "};",
        "static const uint16_t sm64_saturn_bob_fragment_bsp_ref_ranges[SM64_SATURN_BOB_FRAGMENT_BSP_NODE_COUNT][2] = {",
    ]
    lines.extend("    {%dU, %dU}," % tuple(node["ref_range"])
                 for node in bsp["nodes"])
    lines += [
        "};",
        "static const uint16_t sm64_saturn_bob_fragment_bsp_refs[SM64_SATURN_BOB_FRAGMENT_BSP_REF_COUNT] = {",
    ]
    refs = bsp["refs"]
    lines.extend("    " + ", ".join(str(value) + "U" for value in refs[offset:offset + 16]) + ","
                 for offset in range(0, len(refs), 16))
    lines += [
        "};",
        "static const sm64_saturn_bob_fragment_primitive_t sm64_saturn_bob_fragment_primitives[SM64_SATURN_BOB_FRAGMENT_PRIMITIVE_COUNT] = {",
    ]
    for primitive in primitives:
        lines.append(
            "    {{%d, %d, %d, %d}, %d, %d, {%d, %d, %d}, %d, %d, %dU, %dU}," % (
                *primitive["indices"], primitive["source0"],
                primitive["source1"],
                *primitive["rgb"], primitive["textured"],
                primitive["tile_size"], primitive["tile_offset"],
                primitive["clut_offset"],
            )
        )
    lines += ["};", "#endif", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mesh", type=Path, required=True)
    parser.add_argument("--scene", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit(
        json.loads(args.mesh.read_text(encoding="utf-8")),
        json.loads(args.scene.read_text(encoding="utf-8"))), encoding="utf-8")


if __name__ == "__main__":
    main()
