#!/usr/bin/env python3
"""Emit a small C view of the already-validated BOB Mesh IR v2 bank."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def c_array(values: list[object], width: int = 12) -> list[str]:
    lines: list[str] = []
    for offset in range(0, len(values), width):
        lines.append("    " + ", ".join(str(value) for value in values[offset:offset + width]) + ",")
    return lines


def emit(mesh: dict[str, object], manifest: dict[str, object]) -> str:
    entries = {int(entry["source_triangle"]): entry for entry in manifest["entries"]}
    # VDP1 textured triangle tiles use the shared castleviewer A/B/C/C
    # lowering. The offline affine companion is not a runtime vertex.
    positions = [tuple(point) for point in mesh["positions"]]
    materials = {int(material["id"]): material for material in mesh["materials"]}
    primitives: list[dict[str, object]] = []
    for primitive in mesh["primitives"]:
        sources = [int(value) for value in primitive["source_triangles"]]
        tile = entries.get(sources[0])
        material = materials[int(primitive["material"])]
        indices = [int(value) for value in primitive["indices"]]
        if len(indices) != 4:
            raise ValueError("compiled primitive must have four VDP1 corners")
        primitives.append({
            "indices": indices,
            "source0": sources[0],
            "source1": sources[1] if len(sources) > 1 else 0xFFFF,
            "rgb": material["rgb555"],
            "tile_offset": int(tile["bank_offset"]) if tile else 0,
            "clut_offset": int(tile["clut_offset"]) if tile else 0,
            "tile_size": int(tile["tile_size"]) if tile else 0,
            "textured": 1 if tile else 0,
        })
    # Keep one shared position/normal identity while baking deterministic
    # material/primitive masks for runtime LOD selection. The mid tier keeps
    # every source primitive; the far tier drops one of every eight non-
    # route-critical source primitives. source0 remains the stable identity.
    lod_mid = [1] * len(primitives)
    lod_far = [0 if int(primitive["source0"]) % 8 == 0 else 1
               for primitive in primitives]
    lines = [
        "/* Generated by tools/saturn/emit_bob_scene.py; do not edit. */",
        "#ifndef SM64_SATURN_BOB_SCENE_H",
        "#define SM64_SATURN_BOB_SCENE_H",
        "#include <stdint.h>",
        f"#define SM64_SATURN_BOB_POSITION_COUNT {len(positions)}U",
        f"#define SM64_SATURN_BOB_PRIMITIVE_COUNT {len(primitives)}U",
        "typedef struct sm64_saturn_bob_primitive {",
        "    uint16_t indices[4]; uint16_t source0; uint16_t source1;",
        "    uint8_t rgb[3]; uint8_t textured; uint8_t tile_size;",
        "    uint32_t tile_offset; uint32_t clut_offset;",
        "} sm64_saturn_bob_primitive_t;",
        "static const int32_t sm64_saturn_bob_positions[SM64_SATURN_BOB_POSITION_COUNT][3] = {",
    ]
    for point in positions:
        lines.append("    {%d, %d, %d}," % tuple(point))
    lines += [
        "};",
        "static const sm64_saturn_bob_primitive_t sm64_saturn_bob_primitives[SM64_SATURN_BOB_PRIMITIVE_COUNT] = {",
    ]
    for primitive in primitives:
        lines.append(
            "    {{%d, %d, %d, %d}, %d, %d, {%d, %d, %d}, %d, %d, %dU, %dU}," % (
                *primitive["indices"], primitive["source0"], primitive["source1"],
                *primitive["rgb"], primitive["textured"], primitive["tile_size"],
                primitive["tile_offset"], primitive["clut_offset"],
            )
        )
    lines += [
        "};",
        "static const uint8_t sm64_saturn_bob_lod_mid_mask[SM64_SATURN_BOB_PRIMITIVE_COUNT] = {",
    ]
    lines.extend(c_array(lod_mid, width=24))
    lines += [
        "};",
        "static const uint8_t sm64_saturn_bob_lod_far_mask[SM64_SATURN_BOB_PRIMITIVE_COUNT] = {",
    ]
    lines.extend(c_array(lod_far, width=24))
    lines += ["};", "#endif", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mesh", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = emit(
        json.loads(args.mesh.read_text(encoding="utf-8")),
        json.loads(args.manifest.read_text(encoding="utf-8")),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
