#!/usr/bin/env python3
"""Emit the frozen C ABI and identity constants for an S64P root."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

from compile_scene_package import (
    DEPENDENCY_DESCRIPTOR_SIZE, HEADER_SIZE, SECTION_DESCRIPTOR_SIZE,
    SECTION_KINDS, parse_package, publish_or_verify_set,
)
from validate_scene_package import load_payloads, validate_scene_package


def _identifier(value: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not result or result[0].isdigit():
        result = "scene_" + result
    return result


def emit_header(package: bytes, symbol_prefix: str) -> str:
    parsed = parse_package(package)
    prefix = _identifier(symbol_prefix).upper()
    guard = f"SM64_SATURN_{prefix}_S64P_H"
    return f"""/* Generated by tools/saturn/emit_scene_package_header.py; do not edit. */
#ifndef {guard}
#define {guard}

#include "saturn_scene_package_abi.h"

#define {prefix}_S64P_HEADER_SIZE {HEADER_SIZE}U
#define {prefix}_S64P_SECTION_DESCRIPTOR_SIZE {SECTION_DESCRIPTOR_SIZE}U
#define {prefix}_S64P_DEPENDENCY_DESCRIPTOR_SIZE {DEPENDENCY_DESCRIPTOR_SIZE}U
#define {prefix}_S64P_PACKAGE_SIZE {parsed['package_size']}U
#define {prefix}_S64P_LEVEL_ID {parsed['level_id']}U
#define {prefix}_S64P_AREA_ID {parsed['area_id']}U
#define {prefix}_S64P_FLAGS {parsed['flags']}U
#define {prefix}_S64P_PACKAGE_SHA256 \"{parsed['package_sha256']}\"
#define {prefix}_S64P_DEPENDENCY_SET_SHA256 \"{parsed['dependency_set_sha256']}\"

#endif
"""


def emit_abi_header() -> str:
    kinds = "\n".join(
        f"    SM64_SATURN_S64P_{name} = {value},"
        for name, value in SECTION_KINDS.items())
    return f"""/* Generated by tools/saturn/emit_scene_package_header.py; do not edit. */
#ifndef SM64_SATURN_SCENE_PACKAGE_ABI_H
#define SM64_SATURN_SCENE_PACKAGE_ABI_H

#include <stdint.h>

#define SM64_SATURN_S64P_HEADER_SIZE {HEADER_SIZE}U
#define SM64_SATURN_S64P_SECTION_DESCRIPTOR_SIZE {SECTION_DESCRIPTOR_SIZE}U
#define SM64_SATURN_S64P_DEPENDENCY_DESCRIPTOR_SIZE {DEPENDENCY_DESCRIPTOR_SIZE}U

typedef enum sm64_saturn_s64p_section_kind {{
{kinds}
}} sm64_saturn_s64p_section_kind_t;

typedef struct sm64_saturn_scene_package_header {{
    uint32_t magic;
    uint16_t version;
    uint16_t header_size;
    uint32_t package_size;
    uint16_t level_id;
    uint16_t area_id;
    uint16_t section_count;
    uint16_t flags;
    uint8_t package_sha256[32];
    uint8_t dependency_set_sha256[32];
}} sm64_saturn_scene_package_header_t;

typedef struct sm64_saturn_scene_section_descriptor {{
    uint16_t kind;
    uint8_t destination_class;
    uint8_t lifetime;
    uint16_t version;
    uint16_t flags;
    uint32_t offset;
    uint32_t byte_size;
    uint32_t alignment;
    uint32_t dependency_mask;
    uint32_t maximum_scratch;
    uint8_t content_sha256[32];
    uint32_t reserved;
}} sm64_saturn_scene_section_descriptor_t;

typedef struct sm64_saturn_scene_dependency_descriptor {{
    uint16_t payload_kind;
    uint8_t destination_class;
    uint8_t lifetime;
    uint8_t stable_id[32];
    uint32_t byte_count;
    uint32_t alignment;
    uint32_t dependency_mask;
    uint32_t maximum_scratch;
    uint8_t content_sha256[32];
    uint32_t generation;
    uint32_t flags;
    uint32_t reserved;
}} sm64_saturn_scene_dependency_descriptor_t;

typedef char sm64_saturn_s64p_header_size_check[
    sizeof(sm64_saturn_scene_package_header_t) == {HEADER_SIZE} ? 1 : -1];
typedef char sm64_saturn_s64p_section_size_check[
    sizeof(sm64_saturn_scene_section_descriptor_t) == {SECTION_DESCRIPTOR_SIZE} ? 1 : -1];
typedef char sm64_saturn_s64p_dependency_size_check[
    sizeof(sm64_saturn_scene_dependency_descriptor_t) == {DEPENDENCY_DESCRIPTOR_SIZE} ? 1 : -1];

#endif
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--abi-output", type=Path)
    parser.add_argument("--payload-manifest", type=Path)
    parser.add_argument("--payload-root", type=Path)
    parser.add_argument("--symbol-prefix", default="sm64_saturn_scene_package")
    parser.add_argument("--allow-provisional", action="store_true")
    args = parser.parse_args()
    package = args.input.read_bytes()
    validate_scene_package(package, load_payloads(
                               args.payload_manifest, args.payload_root),
                           allow_provisional=args.allow_provisional)
    text = emit_header(package, args.symbol_prefix)
    publications = [(args.output, text.encode("utf-8"))]
    if args.abi_output is not None:
        publications.append(
            (args.abi_output, emit_abi_header().encode("utf-8")))
    publish_or_verify_set(publications)


if __name__ == "__main__":
    main()
