#!/usr/bin/env python3
"""Extract the original Goddard Mario face topology for the Saturn study.

This is a source-to-source data conversion only.  It deliberately preserves
the original vertex positions, triangle order, material IDs, and source
indices from dynlist_mario_face.c; VDP1 projection and material conversion
remain in the Saturn renderer.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


def initializer_body(source: str, name: str, dimensions: str) -> str:
    match = re.search(
        rf"static\s+{re.escape(dimensions)}\s+{re.escape(name)}\[\]\[\d+\]\s*=\s*\{{(.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"could not locate {name}")
    return match.group(1)


def rows(body: str, count: int) -> list[tuple[int, ...]]:
    pattern = r"\{\s*" + r"\s*,\s*".join([r"(-?\d+)"] * count) + r"\s*\}"
    return [tuple(map(int, match)) for match in re.findall(pattern, body)]


def materials(source: str) -> list[tuple[int, int, int]]:
    """Convert the source material ambient RGB floats to Saturn's 5-bit RGB."""
    matches = re.findall(
        r"SetId\((\d+)\),\s*SetAmbient\(([0-9.]+),\s*([0-9.]+),\s*([0-9.]+)\)",
        source,
    )
    result: dict[int, tuple[int, int, int]] = {}
    for material, red, green, blue in matches:
        result[int(material)] = tuple(round(float(value) * 31) for value in (red, green, blue))
    if sorted(result) != list(range(8)):
        raise ValueError("expected material IDs 0 through 7")
    return [result[index] for index in range(8)]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    text = args.input.read_text(encoding="utf-8")
    vertices = rows(initializer_body(text, "mario_Face_VtxData", "s16"), 3)
    faces = rows(initializer_body(text, "mario_Face_FaceData", "u16"), 4)
    face_materials = materials(text)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    lines = [
        "/* Generated by tools/saturn/extract_introface_mesh.py; do not edit. */",
        "/* Source: src/goddard/dynlists/dynlist_mario_face.c",
        f" * SHA-256: {digest}",
        " * Reuse: direct data conversion; vertices and triangles are unchanged. */",
        "#ifndef SM64_SATURN_INTROFACE_MARIO_FACE_MESH_H",
        "#define SM64_SATURN_INTROFACE_MARIO_FACE_MESH_H",
        "",
        f"#define SM64_FACE_VERTEX_COUNT {len(vertices)}U",
        f"#define SM64_FACE_TRIANGLE_COUNT {len(faces)}U",
        "static const int16_t sm64_face_vertices[SM64_FACE_VERTEX_COUNT][3] = {",
    ]
    lines += [f"    {{{x}, {y}, {z}}}," for x, y, z in vertices]
    lines += ["};", "", "/* material, source vertex indices a/b/c */", "static const uint16_t sm64_face_triangles[SM64_FACE_TRIANGLE_COUNT][4] = {"]
    lines += [f"    {{{material}, {a}, {b}, {c}}}," for material, a, b, c in faces]
    lines += ["};", "", "/* RGB555 values converted from the original SetAmbient material values. */", "static const uint8_t sm64_face_material_rgb[8][3] = {"]
    lines += [f"    {{{red}, {green}, {blue}}}," for red, green, blue in face_materials]
    lines += ["};", "", "#endif", ""]
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
