#!/usr/bin/env python3
"""Extract the original Goddard Mario face topology for the Saturn study.

This is a source-to-source data conversion only.  It deliberately preserves
the original vertex positions, triangle order, material IDs, and source
indices from dynlist_mario_face.c; VDP1 projection and material conversion
remain in the Saturn renderer.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import re
from pathlib import Path


def initializer_body(source: str, name: str, dimensions: str) -> str:
    match = re.search(
        rf"static\s+{re.escape(dimensions)}\s+{re.escape(name)}\[\]\[\d+\]\s*=\s*\{{(.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"could not locate {name}")
    return match.group(1)


def rows(body: str, count: int) -> list[tuple[int, ...]]:
    pattern = r"\{\s*" + r"\s*,\s*".join([r"(-?\d+)"] * count) + r"\s*\}"
    return [tuple(map(int, match)) for match in re.findall(pattern, body)]


def materials(source: str) -> list[tuple[int, int, int]]:
    """Convert the source material ambient RGB floats to Saturn's 5-bit RGB."""
    matches = re.findall(
        r"SetId\((\d+)\),\s*SetAmbient\(([0-9.]+),\s*([0-9.]+),\s*([0-9.]+)\)",
        source,
    )
    result: dict[int, tuple[int, int, int]] = {}
    for material, red, green, blue in matches:
        result[int(material)] = tuple(round(float(value) * 31) for value in (red, green, blue))
    if sorted(result) != list(range(8)):
        raise ValueError("expected material IDs 0 through 7")
    return [result[index] for index in range(8)]


def named_rows(source: str, name: str, count: int) -> list[tuple[int, ...]]:
    match = re.search(rf"static\s+\w+\s+{re.escape(name)}\[\]\[\d+\]\s*=\s*\{{(.*?)\}};", source, re.DOTALL)
    if match is None:
        raise ValueError(f"could not locate {name}")
    return rows(match.group(1), count)


def group_materials(source: str, group: str) -> list[tuple[int, int, int]]:
    match = re.search(rf"StartGroup\({re.escape(group)}\),(.*?)EndGroup", source, re.DOTALL)
    if match is None:
        raise ValueError(f"could not locate {group}")
    entries = re.findall(r"SetId\((\d+)\),\s*SetAmbient\(([0-9.]+),\s*([0-9.]+),\s*([0-9.]+)\)", match.group(1))
    result = {int(material): tuple(round(float(value) * 31) for value in (red, green, blue)) for material, red, green, blue in entries}
    if sorted(result) != list(range(4)):
        raise ValueError(f"expected eye material IDs 0 through 3 in {group}")
    return [result[index] for index in range(4)]


def rotate_xyz(vertex: tuple[int, int, int], rotation: tuple[float, float, float]) -> tuple[float, float, float]:
    x, y, z = vertex
    for axis, degrees in zip("xyz", rotation):
        cosine, sine = math.cos(math.radians(degrees)), math.sin(math.radians(degrees))
        if axis == "x":
            y, z = y * cosine - z * sine, y * sine + z * cosine
        elif axis == "y":
            x, z = x * cosine + z * sine, -x * sine + z * cosine
        else:
            x, y = x * cosine - y * sine, x * sine + y * cosine
    return x, y, z


def eye_world_vertices(vertices: list[tuple[int, int, int]], joint_rotation: tuple[float, float, float], net_rotation: tuple[float, float, float], net_offset: tuple[float, float, float]) -> list[tuple[int, int, int]]:
    converted = []
    for vertex in vertices:
        x, y, z = rotate_xyz(rotate_xyz(vertex, joint_rotation), net_rotation)
        converted.append((round(x + net_offset[0]), round(y + net_offset[1]), round(z + net_offset[2])))
    return converted


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--eyes-input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    text = args.input.read_text(encoding="utf-8")
    eyes_text = args.eyes_input.read_text(encoding="utf-8")
    vertices = rows(initializer_body(text, "mario_Face_VtxData", "s16"), 3)
    faces = rows(initializer_body(text, "mario_Face_FaceData", "u16"), 4)
    face_materials = materials(text)
    right_eye = eye_world_vertices(named_rows(eyes_text, "verts_mario_eye_right", 3), (184.483, -178.885, 82.485), (90.0, 180.0, 0.0), (29.7, 192.4, -3.0))
    left_eye = eye_world_vertices(named_rows(eyes_text, "verts_mario_eye_left", 3), (-6.873, 0.206, -97.461), (-90.0, 0.0, 0.0), (-29.0, 192.3, -2.0))
    right_eye_faces = named_rows(eyes_text, "facedata_mario_eye_right", 4)
    left_eye_faces = named_rows(eyes_text, "facedata_mario_eye_left", 4)
    right_eye_materials = group_materials(eyes_text, "DYNOBJ_MARIO_RIGHT_EYE_MTL_GROUP")
    left_eye_materials = group_materials(eyes_text, "DYNOBJ_MARIO_LEFT_EYE_MTL_GROUP")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    lines = [
        "/* Generated by tools/saturn/extract_introface_mesh.py; do not edit. */",
        "/* Source: src/goddard/dynlists/dynlist_mario_face.c",
        f" * SHA-256: {digest}",
        f" * Eye source: src/goddard/dynlists/dynlists_mario_eyes.c SHA-256: {hashlib.sha256(eyes_text.encode('utf-8')).hexdigest()}",
        " * Reuse: direct data conversion; vertices and triangles are unchanged. */",
        "#ifndef SM64_SATURN_INTROFACE_MARIO_FACE_MESH_H",
        "#define SM64_SATURN_INTROFACE_MARIO_FACE_MESH_H",
        "",
        f"#define SM64_FACE_VERTEX_COUNT {len(vertices)}U",
        f"#define SM64_FACE_TRIANGLE_COUNT {len(faces)}U",
        "static const int16_t sm64_face_vertices[SM64_FACE_VERTEX_COUNT][3] = {",
    ]
    lines += [f"    {{{x}, {y}, {z}}}," for x, y, z in vertices]
    lines += ["};", "", "/* material, source vertex indices a/b/c */", "static const uint16_t sm64_face_triangles[SM64_FACE_TRIANGLE_COUNT][4] = {"]
    lines += [f"    {{{material}, {a}, {b}, {c}}}," for material, a, b, c in faces]
    lines += ["};", "", "/* RGB555 values converted from the original SetAmbient material values. */", "static const uint8_t sm64_face_material_rgb[8][3] = {"]
    lines += [f"    {{{red}, {green}, {blue}}}," for red, green, blue in face_materials]
    lines += ["};", "", f"#define SM64_RIGHT_EYE_VERTEX_COUNT {len(right_eye)}U", f"#define SM64_RIGHT_EYE_TRIANGLE_COUNT {len(right_eye_faces)}U", f"#define SM64_LEFT_EYE_VERTEX_COUNT {len(left_eye)}U", f"#define SM64_LEFT_EYE_TRIANGLE_COUNT {len(left_eye_faces)}U", "/* World-space eye vertices: source local data transformed using the static", " * joint/net rotations and offsets in dynlist_mario_master.c (XYZ Euler). */", "static const int16_t sm64_right_eye_vertices[SM64_RIGHT_EYE_VERTEX_COUNT][3] = {"]
    lines += [f"    {{{x}, {y}, {z}}}," for x, y, z in right_eye]
    lines += ["};", "static const uint16_t sm64_right_eye_triangles[SM64_RIGHT_EYE_TRIANGLE_COUNT][4] = {"]
    lines += [f"    {{{material}, {a}, {b}, {c}}}," for material, a, b, c in right_eye_faces]
    lines += ["};", "static const uint8_t sm64_right_eye_material_rgb[4][3] = {"]
    lines += [f"    {{{red}, {green}, {blue}}}," for red, green, blue in right_eye_materials]
    lines += ["};", "static const int16_t sm64_left_eye_vertices[SM64_LEFT_EYE_VERTEX_COUNT][3] = {"]
    lines += [f"    {{{x}, {y}, {z}}}," for x, y, z in left_eye]
    lines += ["};", "static const uint16_t sm64_left_eye_triangles[SM64_LEFT_EYE_TRIANGLE_COUNT][4] = {"]
    lines += [f"    {{{material}, {a}, {b}, {c}}}," for material, a, b, c in left_eye_faces]
    lines += ["};", "static const uint8_t sm64_left_eye_material_rgb[4][3] = {"]
    lines += [f"    {{{red}, {green}, {blue}}}," for red, green, blue in left_eye_materials]
    lines += ["};", "", "#endif", ""]
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
