"""Generate a Q16.16 mirror of SM64's f32 sine/cosine tables.

The engine's trig is table-driven (math_util.h: sins(x) =
gSineTable[(u16)(x) >> 4], gCosineTable = gSineTable + 0x400). The Saturn
render-matrix kernels need the SAME values in Q16.16 -- converted from the
exact f32 table entries, not recomputed ideal sines, so fixed-point results
stay semantically anchored to the source engine's own data.

Output is a committed generated file; re-run this tool only if
include/trig_tables.inc.c ever changes (it is original game data and
should not).
"""
import re
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "include" / "trig_tables.inc.c"
OUTPUT = REPO / "src" / "port" / "saturn" / "gfx" / "saturn_trig_q16.inc.c"

FLOAT_RE = re.compile(r"(-?(?:\d+\.\d*(?:e[+-]?\d+)?f?|0x[0-9a-fA-F.p+-]+f?|\d+f?))\s*,")


def parse_trig_tables(path):
    # include/trig_tables.inc.c holds gSineTable then gCosineTable back to
    # back (0x400 + 0x1000 = 0x1400 f32 entries) -- but immediately after
    # that comes a THIRD array, gArctanTable (s16, bare hex integers like
    # 0x000A). That table must never enter this scan: a hex literal with
    # no A-F letters (e.g. 0x0014) fails FLOAT_RE's "0x" branch as a whole,
    # but the scanner then resumes right after the failed "0x" and matches
    # the plain-decimal branch against the trailing digits alone ("0014"
    # -> 14.0), silently inflating the count. Bounding the scan to end at
    # gArctanTable's declaration keeps this correct regardless of what any
    # regex alternative could match on data that was never meant to be read.
    text = path.read_text()
    region = text[:text.index("gArctanTable")]
    values = []
    for raw in FLOAT_RE.findall(region):
        raw = raw.rstrip("f")
        values.append(float.fromhex(raw) if raw.startswith(("0x", "-0x"))
                      else float(raw))
    return values


def to_q16(f):
    scaled = f * 65536.0
    # round half away from zero, symmetric for negative values
    q = int(scaled + 0.5) if scaled >= 0 else -int(-scaled + 0.5)
    assert -(1 << 31) <= q < (1 << 31), f"{f} out of Q16.16 range"
    return q


def main():
    floats = parse_trig_tables(SOURCE)
    if len(floats) != 0x1400:
        print(f"ERROR: expected 0x1400 table entries, parsed {len(floats)}",
              file=sys.stderr)
        return 1
    lines = [
        "/* GENERATED by tools/saturn/gen_trig_q16.py -- do not edit.",
        " * Q16.16 conversion of include/trig_tables.inc.c's exact f32",
        " * values (round half away from zero). Layout mirrors",
        " * math_util.h: entries [0x000..0x3FF] are the sine table's",
        " * first quadrant span, [0x400..0x13FF] the cosine table, with",
        " * sine reads at index >= 0x400 intentionally overflowing into",
        " * the cosine data exactly as the f32 original does. */",
        "#include <stdint.h>",
        "",
        "const int32_t gSaturnSineTableQ16[0x1400] = {",
    ]
    for i in range(0, 0x1400, 8):
        chunk = ", ".join(str(to_q16(f)) for f in floats[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT} ({len(floats)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
