#!/usr/bin/env python3
# tools/saturn/gen_sourceboot_sky_gradient.py
"""Bake sourceboot's boot-time sky gradient into a compile-time constant.

sourceboot_init_sky_gradient() (src/port/saturn/sourceboot/main.c) fills a
224-entry rgb1555_t array with a pure integer-arithmetic gradient once at
boot, DMAs it to VDP2 VRAM via vdp2_scrn_back_buffer_set(), and never reads
or writes it again. It therefore never needed to be a runtime-computed,
mutable HWRAM buffer -- this script reproduces that exact arithmetic at
build time so the array can ship as `static const` instead. The project's
linker script (src/port/saturn/sourceboot/sourceboot-cart.x) automatically
routes every *sm64-port*(.rodata) into the 4 MiB DRAM cartridge rather than
HWRAM, so this recovers 224 * sizeof(rgb1555_t) = 448 bytes of HWRAM for
free (2026-08-07 memory-budget audit, Finding 2).

RGB1555 packing mirrors extract_mario_textures.saturn_rgb1555's already
hardware-verified layout: raw = msb<<15 | blue<<10 | green<<5 | red. See
that function's docstring for the regression ("turns blue Castle brick red")
that pinned this bit order down originally -- it is not re-derived here from
the union's C bitfield declaration order, which is compiler/ABI-defined and
not safe to guess from source alone.

The fill-loop arithmetic below mirrors sourceboot_init_sky_gradient() line
for line, including its truncating integer division. This must produce
bit-identical output to the C loop it replaces, not a visual approximation.
"""
from __future__ import annotations

BACKSCREEN_LINES = 224


def rgb1555_pack(msb: int, r: int, g: int, b: int) -> int:
    return ((msb & 0x1) << 15) | ((b & 0x1F) << 10) | ((g & 0x1F) << 5) | (r & 0x1F)


def compute_gradient(lines: int = BACKSCREEN_LINES) -> list[int]:
    """Reproduces sourceboot_init_sky_gradient()'s fill loop exactly.

    denom is always lines - 1 (223 for the real 224-line backscreen), matching
    the C loop's `SOURCEBOOT_BACKSCREEN_LINES - 1U`. Python's `//` truncates
    toward negative infinity in general, but every operand here is
    non-negative, so it matches C's truncation-toward-zero integer division
    exactly for every value this loop ever produces.
    """
    denom = lines - 1
    words = []
    for line in range(lines):
        t = denom - line
        r = 1 + (t * 1) // denom
        g = 2 + (t * 8) // denom
        b = 8 + (t * 15) // denom
        words.append(rgb1555_pack(1, r, g, b))
    return words


def build_header(lines: int = BACKSCREEN_LINES) -> str:
    words = compute_gradient(lines)
    header_lines = [
        "/* Generated by tools/saturn/gen_sourceboot_sky_gradient.py. Do not edit by hand. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define SOURCEBOOT_SKY_GRADIENT_GENERATED_LINES {lines}U",
        f"static const rgb1555_t sourceboot_sky_gradient_generated[{lines}] = {{",
    ]
    header_lines += [
        "    " + " ".join(f"{{ .raw = 0x{word:04X} }}," for word in words[i : i + 8])
        for i in range(0, len(words), 8)
    ]
    header_lines.append("};")
    return "\n".join(header_lines) + "\n"


def main() -> None:
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
