#!/usr/bin/env python3
"""Generate a deterministic, copyright-free signed PCM8 proof bank."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SAMPLE_RATE = 11025
BANK_LIMIT = 32768


def _square(sample_count: int, transitions_per_second: int,
            amplitude: int) -> bytes:
    return bytes(amplitude if ((i * transitions_per_second) // SAMPLE_RATE) & 1 == 0
                 else (-amplitude) & 0xFF for i in range(sample_count))


def _noise_burst(sample_count: int) -> bytes:
    state = 0xACE1
    samples = bytearray()
    for index in range(sample_count):
        state = ((state >> 1) ^ (0xB400 if state & 1 else 0)) & 0xFFFF
        amplitude = 96 * (sample_count - index) // sample_count
        value = amplitude if state & 1 else -amplitude
        samples.append(value & 0xFF)
    return bytes(samples)


def generate_proof_bank(output: Path) -> dict[str, object]:
    output.mkdir(parents=True, exist_ok=True)
    waves = (
        ("low_square_220hz", _square(1102, 440, 64)),
        ("high_square_880hz", _square(1102, 1760, 48)),
        ("decaying_lfsr_noise", _noise_burst(2204)),
    )
    bank = bytearray()
    samples: list[dict[str, object]] = []
    for sample_id, (name, wave) in enumerate(waves):
        if len(bank) & 1:
            bank.append(0)
        offset = len(bank)
        bank.extend(wave)
        samples.append({
            "id": sample_id,
            "name": name,
            "offset": offset,
            "sound_ram_offset": 0x8000 + offset,
            "sample_count": len(wave),
            "sample_rate": SAMPLE_RATE,
            "sha256": hashlib.sha256(wave).hexdigest(),
        })
    if len(bank) > BANK_LIMIT:
        raise ValueError(f"proof bank is {len(bank)} bytes; cap is {BANK_LIMIT}")
    digest = hashlib.sha256(bank).hexdigest()
    manifest: dict[str, object] = {
        "bank_bytes": len(bank),
        "bank_sha256": digest,
        "encoding": "signed-mono-pcm8",
        "license": "CC0-1.0/public-domain dedication",
        "sample_rate": SAMPLE_RATE,
        "samples": samples,
    }
    header_lines = [
        "/* Generated by tools/saturn/gen_pcm_proof_bank.py; do not edit.",
        " * Waveform bytes are dedicated to the public domain under CC0-1.0. */",
        "#ifndef SM64_SATURN_PCM_PROOF_BANK_H",
        "#define SM64_SATURN_PCM_PROOF_BANK_H",
        "",
        f"#define SM64_SATURN_PCM_PROOF_BANK_BYTES {len(bank)}U",
        f"#define SM64_SATURN_PCM_PROOF_BANK_SHA256 \"{digest}\"",
    ]
    for entry in samples:
        prefix = f"SM64_SATURN_PCM_PROOF_{entry['id']}"
        header_lines.extend((
            f"#define {prefix}_OFFSET {entry['offset']}U",
            f"#define {prefix}_SAMPLES {entry['sample_count']}U",
        ))
    header_lines.extend(("", "#endif", ""))
    (output / "pcm_proof_bank.bin").write_bytes(bank)
    (output / "pcm_proof_bank.h").write_text(
        "\n".join(header_lines), encoding="ascii", newline="\n")
    (output / "pcm_proof_bank.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8", newline="\n")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest = generate_proof_bank(args.output)
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
