#!/usr/bin/env python3
"""Generate the sourceboot closure for source-owned collision support data.

The original behavior interpreter owns a static table of behavior scripts.  A
number of those scripts retain pointers to level collision and trajectory
arrays even before a level can instantiate the corresponding object.  The
direct Bob bootstrap therefore compiles those arrays as a small, source-owned
catalog instead of dragging each level's render geometry and textures into the
fixed executable image.

Any level whose ``leveldata.c`` is linked directly must be excluded to avoid
duplicate definitions.  Bob is the default direct level.  The catalog is
source data only: it does not rewrite collision, fabricate a scene, or inspect
a ROM.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PATTERNS = ("collision.inc.c", "trajectory.inc.c")


def catalog_paths(root: Path, excluded_levels: tuple[str, ...]) -> list[Path]:
    levels = root / "levels"
    excluded_roots = tuple((levels / level).resolve() for level in excluded_levels)
    paths = {
        path.resolve()
        for pattern in PATTERNS
        for path in levels.rglob(pattern)
        if not any(path.resolve().is_relative_to(excluded) for excluded in excluded_roots)
    }
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def write_catalog(root: Path, output: Path, excluded_levels: tuple[str, ...]) -> None:
    paths = catalog_paths(root, excluded_levels)
    if not paths:
        raise RuntimeError("no source collision or trajectory fragments found")

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by tools/saturn/prepare_sourceboot_collision_catalog.py.",
        " * Original source data retained by the direct-Bob bootstrap. */",
    ]
    lines.extend(f'#include "{path.relative_to(root).as_posix()}"' for path in paths)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--exclude-level", action="append", default=["bob"])
    args = parser.parse_args()
    write_catalog(args.root.resolve(), args.output, tuple(args.exclude_level))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
