#!/usr/bin/env python3
"""Generate the direct-Bob closure for source-owned collision support data.

The original behavior interpreter owns a static table of behavior scripts.  A
number of those scripts retain pointers to level collision and trajectory
arrays even before a level can instantiate the corresponding object.  The
direct Bob bootstrap therefore compiles those arrays as a small, source-owned
catalog instead of dragging each level's render geometry and textures into the
fixed executable image.

Bob's own arrays stay in ``levels/bob/leveldata.c`` and are deliberately
excluded to avoid duplicate definitions.  The catalog is source data only: it
does not rewrite collision, fabricate a scene, or inspect a ROM.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PATTERNS = ("collision.inc.c", "trajectory.inc.c")


def catalog_paths(root: Path) -> list[Path]:
    levels = root / "levels"
    bob = levels / "bob"
    paths = {
        path.resolve()
        for pattern in PATTERNS
        for path in levels.rglob(pattern)
        if not path.resolve().is_relative_to(bob.resolve())
    }
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def write_catalog(root: Path, output: Path) -> None:
    paths = catalog_paths(root)
    if not paths:
        raise RuntimeError("no source collision or trajectory fragments found")

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by tools/saturn/prepare_sourceboot_collision_catalog.py.",
        " * Original source data retained by the direct-Bob bootstrap. */",
    ]
    lines.extend(f'#include "{path.relative_to(root).as_posix()}"' for path in paths)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    write_catalog(args.root.resolve(), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
